version: "3.8"
services:
  client:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ./motd:/etc/motd
      - ./sshd_config:/etc/ssh/sshd_config
    command: "node server.js"